### ISSUE TITLE
Improvements to sendToClient method

### ISSUE THREAD

**Issue by chanaka3d** [wso2/carbon-uuf#101]
The "sendToClient" method is injecting the variables to the "js" placeholder in the layout. We have the "js" placeholder near the end of the page. When we try to access a variable from a js method that is defined before the sendToClient variable injections, it is giving errors. We can workaround this problem by wrapping our method calls inside document ready method.

 But as an improvement to the "sendToClient"  method can we injection the variables to the header section of the page without depending on the placeholder. If that is not possible then prepending to the headJs will make the variables available to all the other scripts.

**Comment by manuranga** [comment]
I think it should always goto head, this is a bug in our code. giving the dev the option to select is going to complicate things

**Comment by this** [comment]
Closing as repo is [deprecated](cdea864e9a02d830aedceb8e6dc661470a7152a6).
