### ISSUE TITLE
JS, CSS resources included in a fragment are not added when the fragment is directly rendered

### ISSUE THREAD

**Issue by this** [wso2/carbon-uuf#129]
Consider following fragment:
```hbs
{{css "css/some-styles.css"}}
{{js "js/some-script.js"}}
<div>
     <p> some HTML content</p>
</div>
```
If this fragment rendered directly from client-side (via ajax), CSS and JS resources won't be added to the output HTML.

**Comment by this** [comment]
@Kishanthan, @Shan1024, @msmshariq, Need to further discuss a proper solution for this,

**Comment by manuranga** [comment]
Do we need to keep a list of already loaded css and JS? so we don't add it agian.

**Comment by this** [comment]
@manuranga Not sure. May be, when a fragment is directly rendered, instead of just returning the HTML we can return a JSON like following.
```js
{ css: [ "/foo/bar.css", "/foo2/bar2.css" ] // list of CSS resources
  js: [ "foo/barz.js", "foo2/barz2.js" } // list of JS resources
  html: "<div> actual HTML goes here.. </div>"
}
```

**Comment by manuranga** [comment]
Not by default. But how about with a special flag?
`http://url/to/frag?_uufWithMetaData=true`
