### ISSUE TITLE
Show images persisted in a database or in a non-public folder from the uuf app. 

### ISSUE THREAD

**Issue by thanujalk** [wso2/carbon-uuf#138]
- 'src' attribute of the <img> element need to have a valid URL
- Need a way to provide a valid URL for the images persisted in a database or in a non-public folder
ex: user-portal/account/account-setting/user-123.jpg

**Comment by this** [comment]
Closing as repo is [deprecated](cdea864e9a02d830aedceb8e6dc661470a7152a6).
