### ISSUE TITLE
Add {{#form}} helper. This helper should add a hidden input to submit the CSRF token.

### ISSUE THREAD

**Issue by msmshariq** [wso2/carbon-uuf#147]
The {{#form}} helper should take the CSRF token cookie value and append it to the the html <form> as a hidden input. This hidden input field will be used to prevent CSRF attacks.

**Comment by this** [comment]
As per discussions on PR #146, we have implemented `{{csrfToken}}` helper instead of `{{#form}}`.
Fixed in PR #146
