### ISSUE TITLE
i18n support in server-side JS

### ISSUE THREAD

**Issue by this** [wso2/carbon-uuf#160]
Currently UUF only support i18n in Handlebars templates. Need it in server-side JS functions (`onGet`, `onPost`) as well.

(originally reported at https://github.com/wso2/carbon-uuf-common/issues/36)

**Comment by manuranga** [comment]
Maybe we shouldn't do this feature, seems like it's not needed with #166 , which is better

**Comment by this** [comment]
@manuranga Let's reevaluate the necessity of this feature after fixing #166.
