### ISSUE TITLE
component.yaml configuration changes are not reflected until rebuild the server

### ISSUE THREAD

**Issue by IndunilRathnayake** [wso2/carbon-uuf#164]
Configurations which are defined in component.yaml file, are not getting reloaded in "devmode". 
And even it won't reflected restarting the server, after changing the component.yaml in the pack.
Since currently in UUF, it computes final configuration at the build time, need to rebuild the pack to get new changes.

**Comment by this** [comment]
Closing as repo is [deprecated](cdea864e9a02d830aedceb8e6dc661470a7152a6).
