### ISSUE TITLE
Placeholder support for 'i18n' helper

### ISSUE THREAD

**Issue by Shan1024** [wso2/carbon-uuf#166]
Currently`{{i18n}}` helper doesn't support resource string with placeholders (variables).

Example resource entry: `message="User %s cannot be found."`

Should be able to pass the values for the placeholders when we use `{{i18n}}` helper.

**Comment by this** [comment]
Instead of using [printf-style format](https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html), let's use the variable style supported by [java.text.MessageFormat](https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html) class. e.g. `My name is {0}.`

**Comment by manuranga** [comment]
You have already included StringFormat helper, which accepts printf-style format. It's inconsistent for UUF to accept different formatting styles in different Helpers.
Please change both if you want to do so.

**Comment by this** [comment]
I think we don't need the `{{stringFormat}}` helper if we support this requirement.

**Comment by this** [comment]
Created issue #183 for removing `{{stringFormat}}` helper.
