### ISSUE TITLE
Form re-submission on page refresh

### ISSUE THREAD

**Issue by Minoli** [wso2/carbon-uuf#168]
![screenshot from 2017-01-26 12-02-27](https://cloud.githubusercontent.com/assets/9837443/22322226/76453938-e3c0-11e6-9312-f2bf0089c8db.png)
After login error is displayed page refresh asks for form re submission and when continued error message do not get removed.

**Comment by manuranga** [comment]
Need to add `window.location.href = window.location.href;`

**Comment by Minoli** [comment]
The page keeps refreshing when I add window.location.href = window.location.href; in document ready

**Comment by this** [comment]
Closing as repo is [deprecated](cdea864e9a02d830aedceb8e6dc661470a7152a6).
