### ISSUE TITLE
i18n weighted multi language support

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf#173]
Adding support for multiple types, weighted with the quality value syntax:
```
Accept-Language: fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5
```

**Comment by this** [comment]
We should use [Locale.LanguageRange.parse(String ranges)](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.LanguageRange.html#parse-java.lang.String-) to parse the `Accept-Languag` header. Then using [Locale.lookup(List\<Locale.LanguageRange> priorityList, Collection\<Locale> locales)](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#lookup-java.util.List-java.util.Collection-) method we can select the correct locale.
