### ISSUE TITLE
Create documentation for UUF

### ISSUE THREAD

**Issue by roonyh** [wso2/carbon-uuf#179]
Documentation should contain following.

- [x] Basic concepts (No JS/HB/Java)
- [ ] How to write an app (with an example scenario)
- [ ] Best practices - How to do stuff in the correct way
- [ ] Ref Guide
  - [x] JS global functions
  - [ ] Helpers
  - [ ] UUF Configurations (app.yml, component.yml, theme.yml)
  - [ ] UUF Maven plugin (archetypes, goals)

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
