### ISSUE TITLE
Remove {{stringFormat}} helper

### ISSUE THREAD

**Issue by this** [wso2/carbon-uuf#183]
`{{stringFormat}}` helper uses the prinft-style variables (e.g. "My name is %s."). This contradicts with the variable style provided by the `{{i18n}}` helper (e.g. "My name is {0}." see issue #166). This contradiction confuses developers.

**Comment by manuranga** [comment]
@this Please put the PR or commit reference when closing a issue.

**Comment by this** [comment]
@manuranga This issue is not closed :)

**Comment by this** [comment]
@vidurananayakkara Please attend to this issue.
