### ISSUE TITLE
Unhanded exceptions should be logged in console.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/carbon-uuf#185]

**Comment by this** [comment]
We should log 'non-HttpErrorException's before rendering error page for Internal Server Error ([here](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/core/App.java#L153))

**Comment by msmshariq** [comment]
@this, shouldn't we log the exception [here](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/core/App.java#L151) also?

**Comment by manuranga** [comment]
@this @msmshariq 
don't we have to catch `Throwable` there?

**Comment by this** [comment]
> @this, shouldn't we log the exception [here](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/core/App.java#L151) also?
`HttpErrorException`s were thrown to render an error page. So we don't need to log `HttpErrorException`s.

**Comment by this** [comment]
@manuranga we are catching (and log) `Exception`s in `RequestDispatcher` class ([see](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/internal/RequestDispatcher.java#L80)).

**Comment by this** [comment]
@manuranga, @msmshariq Real cause of this issue goes beyond little bit further. We have caught `UUFException` twice, in [`App.renderPage`](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/core/App.java#L152) method and in [`RequestDispatcher.serve`](https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/internal/RequestDispatcher.java#L74). 
The reason we need to catch `UUFException` in `App.renderPage` is that in renderable creators (HBS) `UUFException` thrown when something goes wrong (e.g. calling invalid helper, some exception occurs when executing 'onGet' or 'onPost'). What we should do is give an different exception (e.g. `RenderingException`) for renderable creators to throw. In that way we don't need to catch `UUFException` in `App.renderPage` method, instead we can catch `RenderingException` and log it.

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
