### ISSUE TITLE
add/remove {{secured}} helper to a page doesn't get reloaded in Ddevmode.

### ISSUE THREAD

**Issue by ayshsandu** [wso2/carbon-uuf#186]

**Comment by this** [comment]
Currently 'hot deploying on file change' functionality is implemented at the renderable creator level (in HBS renderable). Hence when a page's template is modified, only the template (HBS Renderable) is reloaded not the whole Page object. IMO, we should move the implementation of 'hot deploying on file change' functionality to the core level, which will result to reload the Page object, thus this issue will be fixed.

**Comment by manuranga** [comment]
Ideally any part of the app changed should create a completely new app object, while re-using unchanged parts of the older. But that is a significant design change.

@dakshika - related to #184

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
