### ISSUE TITLE
Redirting by adding '/' may break for POST

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf#189]
Please test if https://github.com/wso2/carbon-uuf/blob/v1.0.0-m12/components/uuf-core/src/main/java/org/wso2/carbon/uuf/core/App.java#L146 works with POST. This was written only GET in mind. May have to use HTTP status 307.

**Comment by this** [comment]
IMO, POST requests doesn't need URL correction. This correction was done as a SEO (base on this [blog post](https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html)).

**Comment by manuranga** [comment]
Agreed. #226 should address it.
