### ISSUE TITLE
Cannot pass strings with single quotes to inline event handlers

### ISSUE THREAD

**Issue by denuwanthi** [wso2/carbon-uuf#193]
Steps to reproduce:
1. Return a string with a single quote from server-side JS as follows.
```js
onGet(){
     return {question: "Father's middle name ?"};
}
```
2.Now use it in the corresponding Handlebars file
```hbs
<form>
     <input type="button" value="Submit" onclick="showText('{{question}}')"/>
</form>
```
with following client-side JS
```js
function showText(text){
     alert(text);
}
```

Now click on the button. Browser inspect element console will print following error.
`Uncaught SyntaxError: missing ) after argument list`

**Comment by this** [comment]
According to [this test case](https://github.com/jknack/handlebars.java/blob/v4.0.3/handlebars/src/test/java/com/github/jknack/handlebars/i370/Issue370.java#L13) in handlebars.java, single quotes should escape correctly. So this bug has been introduced by UUF.
I think bug happens when the output of the server-side JS is passed in to Handlebars context.

**Comment by manuranga** [comment]
1) Please don't put inline JS in HTML, this is an old practice, people don't do this anymore [1]. In fact, in my opinion, we should block that using `Content-Security-Policy`
2) If you want to send information form backbend-JS to frountend-JS please use `sendToClient` feature of UUF

[1] https://en.wikipedia.org/wiki/Unobtrusive_JavaScript

**Comment by manuranga** [comment]
Using sendToClient
----
```js
onGet(){
     sendToClient("question" , "Father's middle name ?");
     return {};
}
```

```hbs
<form>
     <input type="button" value="Submit" id="quesion-viewer"/>
</form>
```

```js
$("#quesion-viewer").click(function(){
     alert(question);
});
```


Alternatively you can use
----
with existing backend js
```hbs
<form>
     <input type="button" value="Submit" class="quesion-viewer" data-quesion="{{question}}"/>
</form>
```


https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes
