### ISSUE TITLE
Use Content-Security-Policy to blok inline JS

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf#200]
This enforces good practice and prevent XSS.

**Comment by manuranga** [comment]
need to block styles as well https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src

this will improve code quality as well.

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
