### ISSUE TITLE
Logging Java Collections should print elements of it

### ISSUE THREAD

**Issue by rasika** [wso2/carbon-uuf#204]
It is the accepted behaviour that invoking Log.error() with java classes prints classname. However it would make developers life easier if we can print Elements when its a Java Collection.

For instance;

`Log.error(env.request.params);` currently prints "Java.Hashmap". But it would be really benificial if it prints all params available on that collection.

**Comment by manuranga** [comment]
+1, We need to print Object.toString for Java object. so in collections it automatically prints list.

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
