### ISSUE TITLE
Improve 'sendToClient' server-side JS function to output strictly JSON

### ISSUE THREAD

**Issue by manuranga** [wso2/carbon-uuf#213]
Ether we load it as separate json file with json content type
OR
We encode it and using HTML encoding and parse using JSON.parse

This will enhance the security of SendToClient

see https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.233.1_-_HTML_escape_JSON_values_in_an_HTML_context_and_read_the_data_with_JSON.parse

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
