### ISSUE TITLE
Cannot execute 'carbon.sh' right away after extracting UUF product

### ISSUE THREAD

**Issue by this** [wso2/carbon-uuf#218]
Steps to reproduce:
- Build [UUF 1.0.0-m14](https://github.com/wso2/carbon-uuf/tree/v1.0.0-m14) tag `mvn clean install`.
- Navigate to `carbon-uuf/product/target` directory.
- Extract `wso2uuf-1.0.0-m14.zip`.
- Navigate to `./wso2uuf-1.0.0-m14/bin/` directory.
- Try to execute carbon.sh file `./carbon.sh`. You will end-up with the following error message.
```bash
bash: ./carbon.sh: Permission denied
```

`ls -l` command reveals that _carbon.sh_ doesn't have the execution permission.
```
-rw-r--r-- 1 sajith sajith 8930 Apr 10 11:59 carbon.sh
```
By executing `chmod +x carbon.sh` command, one can grant execution permission to the _carbon.sh_ file.
```
-rwxr-xr-x 1 sajith sajith 8930 Apr 10 11:59 carbon.sh
```

_carbon.sh_ should have the execution permission initially (when UUF product zip is extracted) without explicitly granting. This issue wasn't present in [UUF 1.0.0-M13](https://github.com/wso2/carbon-uuf/releases/tag/v1.0.0-m13) release.

**Comment by this** [comment]
@jsdjayanga @Kishanthan Seems like this issue comes with [Carbon Kernel 5.2.0-m3](https://github.com/wso2/carbon-kernel/tree/v5.2.0-m3).

**Comment by cnapagoda** [comment]
Please change file permission into 755[1]

[1]. https://github.com/wso2/carbon-uuf/blob/master/product/src/assembly/bin.xml#L52
