### ISSUE TITLE
Remove string helpers completely

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf#236]
Remove string helpers coming from `com.github.jknack.handlebars.helper.StringHelpers` class completely since the usages of these string helpers are redundant. 

Reasons for removing,

* Some of these functionalities are ideally at best achieved with the use of CSS (`center`, `capitalize`, `abbreviate` etc.)
* Some of the helpers can be achieved by using a simple `if else` (`defaultIfEmpty`)
* Rest of the helpers are hardly used in applications

**Comment by this** [comment]
fixed in #233
