### ISSUE TITLE
Server-side JavaScript function to check permission

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-uuf#259]
A server-side JavaScript function is required to check permission for a resource. An example of a usage of this JavaScript function is as shown below:

```js
if(hasPermission(resourceUri, action)) {
   // user has permission, do something
} else {
  // user doesn't have permission
}
```

For pluggable authorization refer https://github.com/wso2/carbon-uuf/issues/250

**Comment by this** [comment]
Closed as repo is [deprecated](https://github.com/wso2/carbon-uuf/pull/278).
